config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :restaurants do
    resources :reviews
  end

  root 'restaurants#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :user
  has_many :reviews,
        -> { extending WithUserAssociationExtension },
        dependent: :destroy
  validates :name, length: {minimum: 3}, uniqueness: true

  def average_rating
    return 'N/A' if reviews.none?
    reviews.average(:rating)
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant

  validates :rating, inclusion: (1..5)
  validates :user, uniqueness: { scope: :restaurant, message: "has reviewed this restaurant already" }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :restaurants
  has_many :reviews
  has_many :reviewed_restaurants, through: :reviews, source: :restaurant
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

   def self.from_omniauth(auth)
     where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
       user.email = auth.info.email
       user.password = Devise.friendly_token[0,20]
      #  user.name = auth.info.name   # assuming the user model has a name
      #  user.image = auth.info.image # assuming the user model has an image
       # If you are using confirmable and the provider(s) you use validate emails,
       # uncomment the line below to skip the confirmation emails.
       # user.skip_confirmation!
     end
   end

   def self.new_with_session(params, session)
     super.tap do |user|
       if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
         user.email = data["email"] if user.email.blank?
       end
     end
   end

  def has_reviewed?(restaurant)
    reviewed_restaurants.include? restaurant
  end
end

app/models/with_user_association_extension.rb
module WithUserAssociationExtension
  def create_with_user(attributes = {}, user)
   attributes[:user] ||= user
   create(attributes)
  end

  def create_with_user!(attributes = {}, user)
    attributes[:user] ||= user
    create!(attributes)
  end

  def build_with_user(attributes = {}, user)
    attributes[:user] ||= user
    build(attributes)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @restaurants = Restaurant.all
    @users = User.all
    @user = current_user
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @user = current_user
    @restaurant = @user.restaurants.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurants_path
    else
      render 'new'
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def edit
    if current_user.id == Restaurant.find(params[:id]).user_id
      @restaurant = Restaurant.find(params[:id])
    else
      flash[:alert] = 'Cannot edit'
      redirect_to restaurants_path
    end
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to '/restaurants'
  end

  def destroy
    if current_user.id == Restaurant.find(params[:id]).user_id
      @restaurant = Restaurant.find(params[:id])
      @restaurant.destroy
      flash[:notice] = 'Restaurant deleted succesfully'
      redirect_to '/restaurants'
    else
      flash[:alert] = 'Cannot delete'
      redirect_to restaurants_path
    end
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :description)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.build_with_user(review_params, current_user)
    if @review.save
        redirect_to restaurants_path
      else
        if @review.errors[:user]
          redirect_to restaurants_path, alert: 'You have already reviewed this restaurant'
        else
          render :new
        end
      end
  end

  def destroy
    @review = Review.find(params[:id])
    if @review
      @review.destroy
      flash[:notice] = 'Review deleted succesfully'
      redirect_to '/restaurants'
    else
      flash[:alert] = 'Nothing to delete'
      redirect_to restaurants_path
    end
  end

  private

  def review_params
    params.require(:review).permit(:thoughts, :rating)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Yelp
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    - if user_signed_in?
      = link_to "Sign out", destroy_user_session_path, method: :delete
    - else
      = link_to "Sign in", new_user_session_path
      = link_to "Sign up", new_user_registration_path
    %p.notice= notice
    %p.alert= alert
    = yield

app/views/restaurants/edit.html.haml
= form_for @restaurant do |f|
  = f.label :name
  = f.text_field :name
  = f.label :description
  = f.text_area :description
  = f.submit

app/views/restaurants/index.html.haml
- if @restaurants.all.any?
  - @restaurants.all.each do |restaurant|
    %h2= link_to restaurant.name, restaurant_path(restaurant)
    %h4 Average rating: #{restaurant.average_rating.to_i}
    - if restaurant.reviews.any?
      - restaurant.reviews.each do |review|
        = review.thoughts
        = "-"
        = @users.find(review.user_id).email
        %p

    %h4
      = link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant)
      = link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete
      - if @user && !@user.has_reviewed?(restaurant)
        = link_to "Review #{restaurant.name}", new_restaurant_review_path(restaurant)
      - elsif @user && @user.has_reviewed?(restaurant)
        = link_to "Delete Your Review", restaurant_review_path(restaurant, restaurant.reviews.where("user_id=#{@user.id}").first.id), method: :delete

- else
  %h1 No restaurants yet

%a{:href => "restaurants/new"} Add a restaurant

app/views/restaurants/new.html.haml
= form_for @restaurant do |f|
  = f.label :name
  = f.text_field :name
  = f.submit
- if @restaurant.errors.any?
  %section#errors
    %h2
      = pluralize(@restaurant.errors.count, "error")
      prohibited this restaurant from being saved:
    %ul
      - @restaurant.errors.full_messages.each do |error|
        %li= error

app/views/restaurants/show.html.haml
%p= @restaurant.name
%p= @restaurant.description
%p
%h2 Reviews
%ul
  - @restaurant.reviews.each do |review|
    %li
      = review.thoughts
      \:
      \#{review.rating}

app/views/reviews/new.html.haml
= form_for [@restaurant, @review] do |f|
  = f.label :thoughts
  = f.text_area :thoughts
  = f.label :rating
  = f.select :rating, (1..5)
  = f.submit 'Leave Review'